# Site Settings
title: My resume
url: 'https://kkedzierska.github.io'
baseurl: '/' #change it according to your repository name

# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
style: styles-6

#Profile information
name: Katarzyna Kedzierska
tagline: Visiting MSc Student @ Center for Public Health Genomics, UVa
pic: profile.jpg  # /assets/images/ 
summary: "I'm a masters student in biotechnology that recently made a transition from wet lab epigenomics to computational biology. So far I worked with RNA-seq, ATAC-seq and ChIP-seq histone data and recently started a project on SNPs and somatic mutations in cancer."

#sidebar links
email: kzkedzierska@gmail.com
website: kkedzierska.github.io #do not add http://
linkedin: kzkedzierska
github: kkedzierska
twitter: '@EthanePiroshki'
#Update all the sections by editing the files inside _data folder.

# Tracker
# analytics: UA-83979019-1
analytics: UA-109521177-1

# Build settings
encoding: "utf-8"
compress_html: # - http://jch.penibelst.de/
  clippings: all
  ignore:
    envs: development
